[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "cc90a8fb0d743353b561d6ffff5ea4f671510081"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "12e05b8010ce1583d5d155d632bb76944dbe07587f5fa15497b22dea463ee945"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.4%2B0/tailwindcss-3.4.4+0-aarch64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "633ac1f68778f3b23722dadbf00450a80631f8c7"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "54ee1370d36a785df47a1b9cc5edcb112edec861e10981e1f1233d2e2902141b"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.4%2B0/tailwindcss-3.4.4+0-armv7l-linux-gnueabihf.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "9d84eab4365ca2d2a6f567b5f74f5104f5cb1fbc"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "469bc20ed68e5f4f8a8cf495548dbca98217b913a5e0d0be7e060b7e925455a7"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.4%2B0/tailwindcss-3.4.4+0-x86_64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "d8938d62fdd9c679ff5cb1608a858dcccbc2db0b"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "838e08f4cb2a87282ae36c68c2be27812936baa57a9055a1eda48f3cab1efe04"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.4%2B0/tailwindcss-3.4.4+0-aarch64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "eeb6a12037b1948941e59572700aaf32e932f4be"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "4e5b72b6297066a8a187531a7cd13f79cc1aa2fae69954d2f7df7f7a60a22926"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.4%2B0/tailwindcss-3.4.4+0-x86_64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "8b1ab23b94a124a5b8a041a122936785169a9a38"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "b6d3d68831e3d171207fd86d23f0c120e05a88cb187674dd78c1e61bba226e1c"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.4%2B0/tailwindcss-3.4.4+0-aarch64-w64-mingw32.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "3f1bc3d932184e1c4c3f0887e257b5656e9948a3"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "232e09f379c77eb5867ef89c8c0dc945e9fa38919aa34cdc18eecc570366b5f1"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.4%2B0/tailwindcss-3.4.4+0-x86_64-w64-mingw32.tar.gz"
