[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "1a51a13ec2834ff44a1917ca3e60a8ecb25b96f0"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "c92ea986c8d3f1ff52ac26ea1d8ab7518e2fb7aa150d5da2f839ea02fd11ac29"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-4.0.0%2B0/tailwindcss-4.0.0+0-aarch64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "088064e054e0d3ab8073e35bef2a722a9ec1b409"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "c685375a18894db1e8978d8ca79e54d98a9ff2f5dc17999ab86e1aed4d0018e6"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-4.0.0%2B0/tailwindcss-4.0.0+0-x86_64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "f9926493c640faab78a91863e8012f3702d61d0a"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "4dc47e9198a5fcef657c97d8f6b7856f12073a04617bdd0cb5b3871eb03a2a89"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-4.0.0%2B0/tailwindcss-4.0.0+0-aarch64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "00eaa337ae7fda1b1931105c2ac45993748931a0"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "031afad65a9df955b387539c68876245897f7ddb1502236ac431188327344ee2"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-4.0.0%2B0/tailwindcss-4.0.0+0-x86_64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "bab2b6a5c3fba42099a8209ad5ed53b7e12a384a"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "07068df42e43cb93c526611d790bc0dd227a028cdbffb4d246f612db48ae774c"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-4.0.0%2B0/tailwindcss-4.0.0+0-x86_64-w64-mingw32.tar.gz"
