[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "419d731e0c9b1d74f3449b4f29966f75b279a0b1"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "7d6e531cc818ade257424fcb9f568ab20a0ced6940ddac0881b4dee3dfc08540"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.3.6%2B0/tailwindcss-3.3.6+0-aarch64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b10bb3806ccb040b0e2b7f21529ec191bc658c51"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "6625877a73909675026a81cf8e56f5fbfbef8b1fa384c144acf8b753add166af"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.3.6%2B0/tailwindcss-3.3.6+0-armv7l-linux-gnueabihf.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "86d031681f0bb62b2fc0a3fdf7623b07f1e33259"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "1258fc07fe2540b8e5bac9bc2ca678a28b32ec31c5d75e9f7ecae82dfa247106"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.3.6%2B0/tailwindcss-3.3.6+0-x86_64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "7f921c0f82026ff17ffdad4aa2ca53bf5d42b69c"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "9b87efd6177a4280ff6148633d918eb0c1be767354fdef9d2195c526173070b3"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.3.6%2B0/tailwindcss-3.3.6+0-aarch64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "638aac76c1a03c644556d23ac0c87f7928b8bcd3"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "bf95efc535549f9a5d47dae29260e233070c73d71b13c30e420c7aa3be1c0682"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.3.6%2B0/tailwindcss-3.3.6+0-x86_64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "a268e605a1085e766210832037a026d99b970cc1"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "6a11b5ba56d4011ebb6e267d81b24aaba1f848af230a519ca83d8143e30696c3"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.3.6%2B0/tailwindcss-3.3.6+0-aarch64-w64-mingw32.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "2f32c79e69ae20cc20484a9ca6844cfa44c68bb7"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "22de7419cfc00a313ab6e8dd292c9959a99437d5f7ea031864088bfa7a3992d5"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.3.6%2B0/tailwindcss-3.3.6+0-x86_64-w64-mingw32.tar.gz"
