[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "cfa0894cd58f408e2139c381eb88b19e0455c9cb"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "9c02c09cf4893dbb295584009f4222fc9a6c8020160e24c99913e95dcf214079"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.13%2B0/tailwindcss-3.4.13+0-aarch64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6056838c2343485503aff9217dfd7aca3b78256d"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "08340f96da67e4495377392c963c2dd35157b7dff31b43e4898784e20b460b2e"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.13%2B0/tailwindcss-3.4.13+0-armv7l-linux-gnueabihf.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "c4422ea22fff3343096dd0d853e0ce890967a945"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "d7f6163e3b80fdbd445ca0dca94e26d271f98d7a1a68cd18c2f29a436805690d"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.13%2B0/tailwindcss-3.4.13+0-x86_64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "be45710d54639a2cbd69afb63f5e0dcfd0c20ece"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "dcb6101092c29ca04c79f40d4ec809ed5920d3dfc9772f36d60b32ab445d9c51"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.13%2B0/tailwindcss-3.4.13+0-aarch64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "8d58973870f4c47e74415492538ab601fce9e46b"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "c819e7a4cad9d15ef9bd713128d56e2a8b3a3c3fa4e1e01f392086205eb0a03e"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.13%2B0/tailwindcss-3.4.13+0-x86_64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "f081deb386f42e24d213f3a833bd6a07bde8f47b"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "da9e573890a396120e90fd72d676ac4e050a141cae6340a8aedf5c9b330bd26f"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.13%2B0/tailwindcss-3.4.13+0-aarch64-w64-mingw32.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "bf511599cde81863c7a6c69d0abfd848e97632c2"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "6a25117a1a85837a78d5a0813b67d20bd7d678d822c687348f1b31b6dafae9bd"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.13%2B0/tailwindcss-3.4.13+0-x86_64-w64-mingw32.tar.gz"
