[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "67055383f977f8b8e2b76337efde2e517ebe41fa"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "cef35bf25cd47c8149cac695f6960cf77b88521e3222ac72cdd3d30d33e20224"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.3%2B0/tailwindcss-3.4.3+0-aarch64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da3bdf0896be0bbcbb76931cfa23f8b4ce1fcf06"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "f75e44cd493e3d3b508412f4742f8abbc5a27a0e3a65cd59504c4d218da30abf"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.3%2B0/tailwindcss-3.4.3+0-armv7l-linux-gnueabihf.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "f0b77fa1dbbdba42b47ae2558511517f3790845e"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "902225c11df777a553e983d523d8df4e2393b90c8497eebdc9fe2e470d7c5db5"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.3%2B0/tailwindcss-3.4.3+0-x86_64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "ed733603c1fd2d6b09a5b996237f04a320aaa7e7"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "bcb202c93e0a5b560c5827420b30902eff53f8377c1d58446f97e4c9078ad3cc"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.3%2B0/tailwindcss-3.4.3+0-aarch64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "6036ca214d06d4334b451e58f37b94ab54818fd5"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "6ab7ad904ee3ffdff4b6f019ff30e26af5dbd4976bca198b39ccee06a8fa360f"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.3%2B0/tailwindcss-3.4.3+0-x86_64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "65c1fa00c71b5719149aa6194ad51d688e17fa97"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "b5defa21198704f643d285160bc8edda78295a85707e9aa5ebd864e7bff5b21c"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.3%2B0/tailwindcss-3.4.3+0-aarch64-w64-mingw32.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "f0f48d7d6c1c1fac20ed551fa6bd54de7a34d0a0"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "bcc33b044ddf188708c32ccaa7d05124071fa00428f942c4b052c7852d0582c9"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.3%2B0/tailwindcss-3.4.3+0-x86_64-w64-mingw32.tar.gz"
