[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "4d0e8650bc2f70a8cd6939f458a950eb7cd2608f"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "eb20b47ddbb0240f87c6ba3f52bf20ad011f941130a7c4e5201ad8fbbc118030"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.6%2B0/tailwindcss-3.4.6+0-aarch64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "665cda11cf10a6f78f72152ceb2155bf46c2f1f1"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "b08116947efae980cb5b554e8cd6317c464e80dccaf3dde85c4998296c7e0ae8"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.6%2B0/tailwindcss-3.4.6+0-armv7l-linux-gnueabihf.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "4f2143e4a68fda3e3d825caf7eb78df03880b9e4"
libc = "glibc"
os = "linux"

    [[tailwindcss.download]]
    sha256 = "4602d7265422479d3d86ccd5baeee3ccb33ee97eac8d5312f2249046bbe4e23a"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.6%2B0/tailwindcss-3.4.6+0-x86_64-linux-gnu.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "c6c89f35ebb5ac3ca7d87ae2e7a4147e5d362742"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "a2df6885b7a7a85c9ec63e15b03357570c6da987ffa8343512e12358298fc7ac"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.6%2B0/tailwindcss-3.4.6+0-aarch64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "db6b8711572c7e71142ed42b704b9d318641e45a"
os = "macos"

    [[tailwindcss.download]]
    sha256 = "7d3af18a0b9a4d2fdb0b0cffbcf9161a05a92c0e4a8a8e1fd2dc9e332c7b7fb5"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.6%2B0/tailwindcss-3.4.6+0-x86_64-apple-darwin14.tar.gz"
[[tailwindcss]]
arch = "aarch64"
git-tree-sha1 = "c6e3aa219ac1bee0affe1e2e9b00806238964004"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "bb9721ff31fac3985929bfcb62aa1d5a66b5e14d2052d23c2fc6dbd60a9b3e09"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.6%2B0/tailwindcss-3.4.6+0-aarch64-w64-mingw32.tar.gz"
[[tailwindcss]]
arch = "x86_64"
git-tree-sha1 = "6d7aaed538bb878c5a0bb17f25451f512677b524"
os = "windows"

    [[tailwindcss.download]]
    sha256 = "a7439fa43f56d3a5cc876f901ca11ef55befd79dffd87b7387f5a26b65c44768"
    url = "https://github.com/MichaelHatherly/TailwindCSS.jl/releases/download/tailwindcss-3.4.6%2B0/tailwindcss-3.4.6+0-x86_64-w64-mingw32.tar.gz"
