name = "TailwindCSS"
uuid = "70f3efdd-15fb-48e9-aed6-b5748bd45f5a"
authors = ["Michael Hatherly <michaelhatherly@gmail.com>"]
version = "1.0.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
Artifacts = "1.6"
julia = "1.6"
