name = "TailwindCSS"
uuid = "70f3efdd-15fb-48e9-aed6-b5748bd45f5a"
authors = ["Michael Hatherly <michaelhatherly@gmail.com>"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
BetterFileWatching = "c9fd44ac-77b5-486c-9482-9798bd063cc6"

[compat]
julia = "1.6"
